package de.smartsquare.wecky.weckyweb.domain

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "User")
data class User(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String = "",

        @DynamoDBAttribute
        var name: String = "",

        @DynamoDBAttribute
        var email: String = ""
)